version: '3.8'

services:
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=mydb
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - db_data_mysql:/var/lib/mysql
    ports:
      - '3306:3306'

volumes:
  db_data_mysql:
