name: 質問
description: このプロジェクトに対する質問をする際に使用してください。
title: '[Question]: '
labels: ['question']
body:
  - type: markdown
    attributes:
      value: '### Issueの作成前に、既存のIssuesを確認してください'

  - type: textarea
    id: question-target
    attributes:
      label: 質問の対象
      placeholder: 情報が必要な対象を記入してください。
    validations:
      required: true

  - type: textarea
    id: question-summary
    attributes:
      label: 質問内容
      placeholder: 質問内容を記入してください。
    validations:
      required: true
