openapi: 3.0.0
paths:
  /:
    get:
      operationId: AppController_getHello
      parameters: []
      responses:
        '200':
          description: ''
  /danger:
    get:
      operationId: AppController_getDanger
      parameters: []
      responses:
        '200':
          description: ''
  /weapons:
    get:
      operationId: WeaponController_getAllWeapon
      parameters: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: number
                  name:
                    type: string
                  attackPower:
                    type: number
                  attribute:
                    type: string
                    enum:
                      - SWORD
                      - BOW
                required:
                  - id
                  - name
                  - attackPower
                  - attribute
      tags: &ref_1
        - weapons
    post:
      operationId: WeaponController_create
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                attackPower:
                  type: number
                attribute:
                  type: string
                  enum: &ref_0
                    - SWORD
                    - BOW
              required:
                - name
                - attackPower
                - attribute
      responses:
        '201':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: number
                  name:
                    type: string
                  attackPower:
                    type: number
                  attribute:
                    type: string
                    enum: *ref_0
                required:
                  - id
                  - name
                  - attackPower
                  - attribute
      tags: *ref_1
  /weapons/pages:
    get:
      operationId: WeaponController_getAllWeaponWithPages
      parameters:
        - name: includePageCount
          required: true
          in: query
          example: 'true'
          schema:
            type: string
        - name: limit
          required: true
          in: query
          example: '10'
          schema:
            type: string
        - name: page
          required: true
          in: query
          example: '1'
          schema:
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: number
                  name:
                    type: string
                  attackPower:
                    type: number
                  attribute:
                    type: string
                    enum:
                      - SWORD
                      - BOW
                required:
                  - id
                  - name
                  - attackPower
                  - attribute
      tags: *ref_1
  /weapons/{id}:
    get:
      operationId: WeaponController_getWeapon
      parameters:
        - name: id
          required: true
          in: path
          example: '1'
          schema:
            type: string
      responses:
        '200':
          description: ''
      tags: *ref_1
    patch:
      operationId: WeaponController_update
      parameters:
        - name: id
          required: true
          in: path
          example: '1'
          schema:
            type: number
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                attackPower:
                  type: number
                attribute:
                  type: string
                  enum: &ref_2
                    - SWORD
                    - BOW
              required:
                - name
                - attackPower
                - attribute
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: number
                  name:
                    type: string
                  attackPower:
                    type: number
                  attribute:
                    type: string
                    enum: *ref_2
                required:
                  - id
                  - name
                  - attackPower
                  - attribute
      tags: *ref_1
    delete:
      operationId: WeaponController_delete
      parameters:
        - name: id
          required: true
          in: path
          example: '1'
          schema:
            type: string
      responses:
        '204':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: number
                  name:
                    type: string
                  attackPower:
                    type: number
                  attribute:
                    type: string
                    enum:
                      - SWORD
                      - BOW
                required:
                  - id
                  - name
                  - attackPower
                  - attribute
      tags: *ref_1
  /auth/login:
    post:
      operationId: AuthController_login
      parameters: []
      responses:
        '200':
          description: ''
      tags: &ref_3
        - auth
  /auth/me:
    get:
      operationId: AuthController_me
      parameters: []
      responses:
        '200':
          description: ''
      tags: *ref_3
info:
  title: API Doc
  description: API Doc Description
  version: '1.0'
  contact: {}
tags: []
servers: []
components:
  schemas: {}
