openapi: 3.0.0
paths:
  /:
    get:
      operationId: AppController_getHello
      parameters: []
      responses:
        '200':
          description: ''
  /danger:
    get:
      operationId: AppController_getDanger
      parameters: []
      responses:
        '200':
          description: ''
  /weapons/-schema-:
    get:
      operationId: WeaponController_openApiSchema
      parameters: []
      responses:
        '200':
          content:
            application/json; charset=utf-8:
              schema:
                type: object
                properties:
                  id:
                    type: number
                    nullable: false
                    description: The id of the weapon
                    example: 1
                  name:
                    type: string
                    description: The name of the weapon
                    example: Sword
                  attackPower:
                    type: number
                    nullable: false
                    description: The attack power of the weapon
                    example: 10
                  attribute:
                    type: string
                    enum:
                      - SWORD
                      - BOW
                    description: The attribute of the weapon
                    example: SWORD
                required:
                  - id
                  - name
                  - attackPower
                  - attribute
                title: WeaponSchma
                description: The weapon schema
          description: ''
      tags: &ref_0
        - weapons
  /weapons:
    get:
      operationId: WeaponController_getAllWeapon
      parameters: []
      responses:
        '200':
          content:
            application/json; charset=utf-8:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: number
                      nullable: false
                      description: The id of the weapon
                      example: 1
                    name:
                      type: string
                      description: The name of the weapon
                      example: Sword
                    attackPower:
                      type: number
                      nullable: false
                      description: The attack power of the weapon
                      example: 10
                    attribute:
                      type: string
                      enum:
                        - SWORD
                        - BOW
                      description: The attribute of the weapon
                      example: SWORD
                  required:
                    - id
                    - name
                    - attackPower
                    - attribute
                  title: WeaponSchma
                  description: The weapon schema
          description: ''
      tags: *ref_0
    post:
      operationId: WeaponController_create
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: The name of the weapon
                  example: Sword
                attackPower:
                  type: number
                  nullable: false
                  description: The attack power of the weapon
                  example: 10
                attribute:
                  type: string
                  enum:
                    - SWORD
                    - BOW
                  description: The attribute of the weapon
                  example: SWORD
              required:
                - name
                - attackPower
                - attribute
      responses:
        '201':
          content:
            application/json; charset=utf-8:
              schema:
                type: object
                properties:
                  id:
                    type: number
                    nullable: false
                    description: The id of the weapon
                    example: 1
                  name:
                    type: string
                    description: The name of the weapon
                    example: Sword
                  attackPower:
                    type: number
                    nullable: false
                    description: The attack power of the weapon
                    example: 10
                  attribute:
                    type: string
                    enum:
                      - SWORD
                      - BOW
                    description: The attribute of the weapon
                    example: SWORD
                required:
                  - id
                  - name
                  - attackPower
                  - attribute
                title: WeaponSchma
                description: The weapon schema
          description: ''
      tags: *ref_0
  /weapons/pages:
    get:
      operationId: WeaponController_getAllWeaponWithPages
      parameters:
        - name: limit
          required: true
          in: query
          example: '10'
          schema:
            type: string
        - name: page
          required: true
          in: query
          example: '1'
          schema:
            type: string
      responses:
        '200':
          content:
            application/json; charset=utf-8:
              schema: {}
          description: ''
      tags: *ref_0
  /weapons/{id}:
    get:
      operationId: WeaponController_getWeapon
      parameters:
        - name: id
          required: true
          in: path
          example: '1'
          schema:
            type: string
      responses:
        '200':
          content:
            application/json; charset=utf-8:
              schema:
                type: object
                properties:
                  id:
                    type: number
                    nullable: false
                    description: The id of the weapon
                    example: 1
                  name:
                    type: string
                    description: The name of the weapon
                    example: Sword
                  attackPower:
                    type: number
                    nullable: false
                    description: The attack power of the weapon
                    example: 10
                  attribute:
                    type: string
                    enum:
                      - SWORD
                      - BOW
                    description: The attribute of the weapon
                    example: SWORD
                required:
                  - id
                  - name
                  - attackPower
                  - attribute
                title: WeaponSchma
                description: The weapon schema
          description: ''
      tags: *ref_0
    patch:
      operationId: WeaponController_update
      parameters:
        - name: id
          required: true
          in: path
          example: '1'
          schema:
            type: number
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: The name of the weapon
                  example: Sword
                attackPower:
                  type: number
                  nullable: false
                  description: The attack power of the weapon
                  example: 10
                attribute:
                  type: string
                  enum:
                    - SWORD
                    - BOW
                  description: The attribute of the weapon
                  example: SWORD
              required:
                - name
                - attackPower
                - attribute
      responses:
        '200':
          content:
            application/json; charset=utf-8:
              schema:
                type: object
                properties:
                  id:
                    type: number
                    nullable: false
                    description: The id of the weapon
                    example: 1
                  name:
                    type: string
                    description: The name of the weapon
                    example: Sword
                  attackPower:
                    type: number
                    nullable: false
                    description: The attack power of the weapon
                    example: 10
                  attribute:
                    type: string
                    enum:
                      - SWORD
                      - BOW
                    description: The attribute of the weapon
                    example: SWORD
                required:
                  - id
                  - name
                  - attackPower
                  - attribute
                title: WeaponSchma
                description: The weapon schema
          description: ''
      tags: *ref_0
    delete:
      operationId: WeaponController_delete
      parameters:
        - name: id
          required: true
          in: path
          example: '1'
          schema:
            type: string
      responses:
        '200':
          content:
            application/json; charset=utf-8:
              schema:
                type: object
                properties:
                  id:
                    type: number
                    nullable: false
                    description: The id of the weapon
                    example: 1
                  name:
                    type: string
                    description: The name of the weapon
                    example: Sword
                  attackPower:
                    type: number
                    nullable: false
                    description: The attack power of the weapon
                    example: 10
                  attribute:
                    type: string
                    enum:
                      - SWORD
                      - BOW
                    description: The attribute of the weapon
                    example: SWORD
                required:
                  - id
                  - name
                  - attackPower
                  - attribute
                title: WeaponSchma
                description: The weapon schema
          description: ''
      tags: *ref_0
  /auth/login:
    post:
      operationId: AuthController_login
      parameters: []
      responses:
        '200':
          description: ''
      tags: &ref_1
        - auth
  /auth/me:
    get:
      operationId: AuthController_me
      parameters: []
      responses:
        '200':
          description: ''
      tags: *ref_1
info:
  title: API Doc
  description: API Doc Description
  version: '1.0'
  contact: {}
tags: []
servers: []
components:
  schemas: {}
