name: Remove "in progress" label on Issue close

on:
  issues:
    types:
      - closed

jobs:
  remove-label:
    runs-on: ubuntu-latest
    steps:
    - name: Remove "in progress" label
      run: |
        ISSUE_NUMBER=${{ github.event.issue.number }}
        
        while read -r message; do
          label=${echo "$message"}

          if $label === "wip"
            gh issue edit $ISSUE_NUMBER --remove-label "wip"
          fi
        done < <(gh issue view $ISSUE_NUMBER --json labels --jq '.labels[].name')

      env:
        GH_TOKEN: ${{ secrets.TOKEN }}
